### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by mapulse** [qewerty/moto.old#24]
build/linux2/libmoto/moto-anim-node.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #include "libmotoutil/moto-gl.h"
 ^
build/linux2/libmoto/moto-anim-node.c:1:0: error: CPU you selected does not support x86-64 instruction set
scons: **\* [build/linux2/libmoto/moto-anim-node.os] Error 1
scons: building terminated because of errors.

how do i fix?

**Comment by qewerty** [comment]
The project is dead. Sorry

**Comment by mapulse** [comment]
:(, happy new project
